version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      DATABASE_NAME: hottip
      POSTGRES_USER: hottip
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  web:
    image: hottip
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_HOST: db
      DATABASE_NAME: hottip
      DATABASE_USER: hottip
      DATABASE_PASSWORD: password
      HOTTIP_BATCH_MODE: 0
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/app

  batch:
    image: hottip
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    env_file: .env
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_HOST: db
      DATABASE_NAME: hottip
      DATABASE_USER: hottip
      DATABASE_PASSWORD: password
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_CREATESUPERUSER: "on"
      HOTTIP_BATCH_MODE: 1
    depends_on:
      - db
    volumes:
      - .:/app


